[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "frontend/out"

[build.environment]
  NEXT_PUBLIC_BASE_PATH = "/"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-domain.example.com/api/:splat"
  status = 200
  force = true

